<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE error-codes [

  <!ELEMENT error-codes (facility+)>
  <!ELEMENT facility    (code+)>
  <!ELEMENT code        (message,remarks?)>
  <!ELEMENT message     (#PCDATA)>
  <!ELEMENT remarks     (#PCDATA|para)*>
  <!ELEMENT para        (#PCDATA)>

  <!-- facility's "hex" attrib is a 12-bit integer in hexadecimal notation. -->
  <!ATTLIST facility   hex      CDATA                                 #REQUIRED>
  <!-- 
    facility's "name" attribute is only used internally. It will not 
    appear in the generated code, but should be a valid identifier.
    A good idea is to only use [a-zA-Z].
    -->
  <!ATTLIST facility   name     ID                                    #REQUIRED>
  <!-- 
    code's "hex" attribute is a 15-bit integer in hexadecimal notation.
    Or rather, actually it's 16 bits, but bit 16 is used to carry other 
    information from the I/O controllers so it should never be set. 
    -->
  <!ATTLIST code       hex      CDATA                                 #REQUIRED>
  <!-- 
    code's "name" attribute is the identifier for the code, and will 
    be used as a #define in the native h file, and as a const in the C#
    generated.
    -->
  <!ATTLIST code       name     ID                                    #REQUIRED>
  <!-- 
    code's "severity" attribute; constitutes the four highest order bits:
    Success       0x0
    Informational 0x1
    Warning       0x2
    Error         0x3
    -->
  <!ATTLIST code       severity (Success|Informational|Warning|Error) #REQUIRED>

]>
<error-codes>
  <!-- 
  Header file containing all Starcounter error codes. Note that error code 0 is reserved 
  for no error (the operation was successful). 
  
  Error code standards: 
  
  1. EVERY error should have an error code. Note that errors that hasn't a corresponding 
     error code is assigned the unspecified error code so they to have an error code. This 
     error code should be reserved for user code only however (non Starcounter code). 
     
  2. EVERY error code should be defined in this file. This way we can keep track of which 
     error codes exists and a common source for documentation (with the bonus that it's 
     easier to avoid duplicates). 
     
  3. EVERY error code should be placed in the correct category (see below). 
  
  4. An assigned error code must never be reused. To clarify: If the error code 5 is removed 
     then no error code added in the future is allowed to be assigned the value 5. The reason
     for this is to avoid having users, or software, recognizing the error code to make the 
     wrong assumption as to which error it refers to. 
     
  5. An error code should, if possible, be so specific that it pinpoints a specific type of 
     error in a specific module. General errors like "can't write to file" should be avoided.
     If a log file couldn't be written to because the disk was full this should be indicated 
     by a different error code then if a backup couldn't be completed for the same reason. 
     This way an error code could indicate a specific error without any additional data. 
     
  6. When an error occurs that requires additional data to be interpreted it should be logged 
     separatly and generate another, more general error, indicating that the first error occured. 
     We refer to this as an internal error. Typically an internal error isn't an error that 
     can be caused by, or handled by, the caller. An example is when an unexpected file error 
     causes something like a backup to fail. In order to see what the problem is it will probably 
     help to have things like path information and the underlying error code. We therefore log an 
     "unexpected backup error" and send an error to the caller with an error code indicating that 
     backup failed: see log files for more information. This is also a good approach because you 
     often can't trust user code to log errors correctly, making sure an error is logged correcly 
     before passing it on to the caller is a good way to make sure there is relevant information 
     about the error available. Critical errors that takes down the process also falls under this 
     category (can't write to transaction log, assertion failures etc.). 
     
  7. Error codes must be documented in order by value in this file (an error code with the value 5 must 
     be placed after an error code with the value 3 but before an error code with the value 6). The 
     reason for this is simply because it's easier to read as documetation and it's easier to assign a 
     new error code since it's easier to determine which error code currently has the greatest value. 

  8. No error code definitition is more then 32 characters in length.
  
  9. When formulating error messages, consider the design guidelines used when designing exception
     messages. Please consult any of these resources for guidance:
     
        http://msdn.microsoft.com/en-us/library/ms229056.aspx
        http://blogs.msdn.com/b/brada/archive/2004/01/28/64255.aspx
        http://blogs.msdn.com/b/kcwalina/archive/2007/01/30/exceptionhierarchies.aspx
        http://msdn.microsoft.com/en-us/library/windows/desktop/aa511267.aspx
        http://developer.android.com/design/style/writing.html
        
     Longer error messages gain from being divided into a compact "brief" as a first sentence,
     formulating the problem. If so, the error coding API's can be used to show the brief in a
     title-like context and the full message in a longer section below.
     
     Example:
     
     "The database can not start because the executable file could not be found in the
     installation folder."
     
     can be rewritten as
     
     "The database could not start. When trying to start the database, the executable file
     was not found in the installation folder."
     
  Error code categories: 
   
  1. General error. Error codes that doesn't fit in any of the other groups. Out of memory is a a
     good example, it can occur anywhere. 
  
  2. Startup and shutdown error codes. Codes for errors occuring during database startup or shutdown.
     Usually caused by a faulty installation, bad application arguments or faulty configuration
     settings.
     
  3. General I/O error codes.
     
  4. Database error codes. Codes for database errors that can be caused by faulty user code or
     transactions as well as errors that is the result of some previous internal error (like if
     unable to create dump).
  
  5. Session errors.
  
  6. Unexpected internal errors. Usually representing unexpected errors returned from API
     functions, corrupted files or invalid input.
  
  7. Sql provider errors.
  
  8. Transaction abort codes.
  
  9. (Not used; removed)
  
  10. Management error codes. Codes that pinpoints different management tasks, such as the starting,
      stopping, deleting of databases, communicating with servers (i.e. management servers) and such.
      These codes are used in management components such as the client hosting management library and
      in tools/components built on top of that, such as Starcounter Administrator and our Visual
      Studio extensions.
      
  11. Installer error codes.
      
  12. Development specific error codes. These codes represent problems that are specific to the
      development of Starcounter code libraries and clients.
      
  -->

  <facility name="Unspecified" hex="0000">
    <code hex="3E7" severity="Error" name="ScErrUnspecified">
      <message>An unspecified error caused the operation to fail.</message>
    </code>
  </facility>

  <!-- General error codes. -->
  <facility name="General" hex="0001">
    <code hex="0001" severity="Error" name="ScErrBadArguments">
      <message>One or more arguments was invalid.</message>
    </code>
    <code hex="0002" severity="Error" name="ScErrCodeNotEnhanced">
      <message>Code not enhanced.</message>
      <remarks>
        Runtime error occuring when accessing code that needs to be enhanced in order to work, but
        for some reason hasn't,
      </remarks>
    </code>
    <code hex="0003" severity="Error" name="ScErrOutOfMemory">
      <message>Operation failed because needed memory couldn't be allocated.</message>
    </code>
    <code hex="0004" severity="Error" name="ScErrThreadNotAttached">
      <message>The operation failed because the current thread wasn't attached to the scheduler.</message>
      <remarks>This can either indicate that the thread is temporarily detached from the scheduler or that it isn't a worker thread. Only certain operations differs between the two.</remarks>
    </code>
    <code hex="0005" severity="Error" name="ScErrNotSupported">
      <message>The requested operation is not supported on the specific object.</message>
    </code>
    <code hex="0006" severity="Error" name="ScErrNotAWorkerThread">
      <message>The operation failed because the calling thread isn't a worker thread.</message>
    </code>
    <code hex="0007" severity="Error" name="ScErrThreadNotDetached">
      <message>The operation failed because the current thread was attached to the scheduler and detached thread was expected.</message>
    </code>
    <code hex="0008" severity="Error" name="ScErrThreadYieldBlocked">
      <message>The operation failed because it required the thread to yield but yield was blocked.</message>
    </code>
    <code hex="0009" severity="Error" name="ScErrCounterMismatch">
      <message>Generic error code for counter mismatch.</message>
    </code>
    <code hex="000A" severity="Error" name="ScErrCounterOverflow">
      <message>Generic error code for counter overflow.</message>
    </code>
	  <code hex="000B" severity="Error" name="ScErrStackOverflow">
		  <message>A stack overflow has been detected.</message>
	  </code>
    <code hex="000C" severity="Error" name="ScErrWaitTimeout">
      <message>The wait timed out before the object was signaled.</message>
    </code>
    <code hex="000D" severity="Error" name="ScErrMaxThreadsReached">
      <message>
       The operation failed because the maximum number of worker threads has been reached and the
       operation required the scheduler to create additional worker threads.
      </message>
      <remarks>
       This error can occur when a large number of worker threads are blocked.
      </remarks>
    </code>
    <code hex="000E" severity="Error" name="ScErrCantCreateUuid">
      <message>
        Failed to generate an UUID.
      </message>
    </code>
    <code hex="0010" severity="Error" name="ScErrMutexNotOwned">
      <message>
        Operation failed because of an attempt to release ownership of a mutex
        not owned by the current thread.
      </message>
    </code>
    <code hex="0011" severity="Error" name="ScErrWouldBlock">
      <message>A non blocking operation failed because if would be required to block.</message>
    </code>
    <code hex="0012" severity="Error" name="ScErrUnresposiveThreadStall">
      <message>
        A cooperatively scheduled worker thread has been unresponsive for an unacceptably long
        period of time.
      </message>
      <remarks>
        <para>
          A cooperatively scheduled worker thread is considered unresponsive when it hasn't yielded
          for more then a minute but this error isn't generated unless the thread has been
          unresponsive for a user configured period of time (2 minutes by default). If a thread is
          detected to be unresponsive but not long enough for the error to be generated, a warning
          is generated instead.
        </para>
        <para>
          The error is likely caused by an infinite loop or a deadlock but could also be caused by
          the thread doing something that doesn't give it the opportunity to yield for a very long
          period of time (which also is a real problem since the stall timeout is configured in
          minutes).
        </para>
      </remarks>
    </code>
    <code hex="0013" severity="Error" name="ScErrThreadsBlockedStall">
      <message>
        All threads available to the scheduler has been blocked for an unacceptably long period of
        time.
      </message>
      <remarks>
        <para>
          The error is likely an indication of a deadlock or a highly contested lock held for a
          very long period of time.
        </para>
      </remarks>
    </code>
    <code hex="0014" severity="Error" name="ScErrTaskCleanupIncomplete">
      <message>
        A task still held resource when terminating that should have been
        released before the task terminated.
      </message>
      <remarks>
        <para>
          Error currently only raised when exclusive environment ownership hasn't been released
          when task terminated. This should not occur.
        </para>
      </remarks>
    </code>
    <code hex="0015" severity="Error" name="ScErrUnyieldingThreadStall">
      <message>
        A cooperatively scheduled worker thread has been unwilling to yield for
        an unacceptably long period of time.
      </message>
    </code>
    <code hex="0016" severity="Error" name="ScErrThreadAutoDetached">
      <message>
        Use of reattach function for manually detached threads on auto detached thread.
      </message>
    </code>
    <code hex="0017" severity="Error" name="ScErrThreadNotAutoDetached">
      <message>
        Use of reattach function for auto detached threads on manually detached thread.
      </message>
    </code>
    <code hex="0018" severity="Error" name="ScErrDebugVerifyFailed">
      <message>
        Generic error code indicating that debug verification failed.
      </message>
    </code>
    <code hex="0019" severity="Error" name="ScErrInvalidOperation">
      <message>Operation invalid for the object's current state.</message>
    </code>
    <code hex="001A" severity="Error" name="ScErrInputQueueFull">
      <message>Operation failed because the target input queue was full.</message>
    </code>
    <code hex="001B" severity="Error" name="ScErrNotImplemented">
      <message>The method, operation or feature is not implemented.</message>
    </code>
    <code hex="001C" severity="Error" name="ScErrEnvVariableNotAccessible">
      <message>Access to an environment variable was not permitted due to the current security settings.</message>
    </code>
    <code hex="001D" severity="Error" name="ScErrBinDirEnvNotFound">
      <message>The environment variable holding the path to the Starcounter installation directory was not found.</message>
    </code>
    <code hex="001E" severity="Error" name="ScErrBadCommandLineFormat">
      <message>The format of the command-line was invalid.</message>
    </code>
    <code hex="001F" severity="Error" name="ScErrBadCommandLineSyntax">
      <message>Command-line arguments didn't match the defined syntax.</message>
    </code>
    <code hex="0020" severity="Error" name="ScErrBadPostSharpLicense">
      <message>The license key used to initialize the PostSharp library was invalid.</message>
    </code>
    <code hex="0021" severity="Error" name="ScErrWrongErrorMessageFormat">
      <message>Parsing an error message string failed due to an incorrect message format.</message>
    </code>
    <code hex="0022" severity="Error" name="ScErrOperationCancelled">
      <message>The operation was cancelled.</message>
      <remarks>
        General error code representing a cancelled operation.
      </remarks>
    </code>
    <code hex="0023" severity="Error" name="ScErrSharedInterfaceOpenDbShm">
      <message>Opening the managed segment with the segment_name failed. Invalid segment or does not exist.</message>
    </code>
    <code hex="0024" severity="Error" name="ScErrFindChunks">
      <message>Could not find the chunks shared memory object.</message>
    </code>
    <code hex="0025" severity="Error" name="ScErrFindSharedChunkPool">
      <message>Could not find the shared_chunk_pool shared memory object.</message>
    </code>
    <code hex="0026" severity="Error" name="ScErrFindCommonSchedInterface">
      <message>Could not find the common_scheduler_interface shared memory object.</message>
    </code>
    <code hex="0027" severity="Error" name="ScErrFindSchedulerInterfaces">
      <message>Could not find the scheduler_interfaces shared memory object.</message>
    </code>
    <code hex="0028" severity="Error" name="ScErrFindCommonClientInterface">
      <message>Could not find the common_client_interface shared memory object.</message>
    </code>
    <code hex="0029" severity="Error" name="ScErrFindClientInterfaces">
      <message>Could not find the client_interfaces shared memory object.</message>
    </code>
    <code hex="002A" severity="Error" name="ScErrFindChannels">
      <message>Could not find the channels shared memory object.</message>
    </code>
    <code hex="002B" severity="Error" name="ScErrOpenSchedulerWorkEvent">
      <message>Failed to open a scheduler work event.</message>
    </code>
    <code hex="002C" severity="Error" name="ScErrOpenClientWorkEvent">
      <message>Failed to open a client work event.</message>
    </code>
    <code hex="002D" severity="Error" name="ScErrOpenSchedNumPoolNotEmptyEv">
      <message>Failed to open a scheduler number pool not empty event.</message>
    </code>
    <code hex="002E" severity="Error" name="ScErrOpenSchedNumPoolNotFullEv">
      <message>Failed to open a scheduler number pool not full event.</message>
    </code>
    <code hex="002F" severity="Error" name="ScErrFormatActiveDbUpdatedEvName">
      <message>Failed to format the active databases updated event name.</message>
    </code>
    <code hex="0030" severity="Error" name="ScErrConvertActiveDbUpdatedEvMBS">
      <message>Failed to convert active databases updated event name to multi-byte string.</message>
    </code>
    <code hex="0031" severity="Error" name="ScErrOpenActiveDbUpdatedEv">
      <message>Failed to open the active databases updated event.</message>
    </code>
    <code hex="0032" severity="Error" name="ScErrIPCMonitorEraseDatabaseName">
      <message>The IPC monitor failed to erase a database name.</message>
    </code>
    <code hex="0033" severity="Error" name="ScErrBoostInterprocessException">
      <message>The IPC monitor trying to open segment boost::interprocess::interprocess_exception caught.</message>
    </code>
    <code hex="0034" severity="Error" name="ScErrTryOpenSegmentUnknownExcept">
      <message>The IPC monitor trying to open segment unknown exception caught.</message>
    </code>
    <code hex="0035" severity="Error" name="ScErrGotClientProcessTypeNotDb">
      <message>The IPC monitor expected database process but got client process type.</message>
    </code>
    <code hex="0036" severity="Error" name="ScErrGotUnknownProcessTypeNotDb">
      <message>The IPC monitor expected database process but got unknown process type.</message>
    </code>
    <code hex="0037" severity="Error" name="ScErrOpenProcessFailedRegDbProc">
      <message>The IPC monitor is trying to register a database process but OpenProcess() failed.</message>
    </code>
    <code hex="0038" severity="Error" name="ScErrIPCMonInsertDbNameActiveDbR">
      <message>The IPC monitor failed to insert database name into active databases register.</message>
    </code>
    <code hex="0039" severity="Error" name="ScErrIPCMonitorInsertSegmentName">
      <message>The IPC monitor failed to insert segment name into the monitor interface.</message>
    </code>
    <code hex="003A" severity="Error" name="ScErrIPCMonFailedNotifyScheduler">
      <message>The IPC monitor failed to notify the scheduler on the given channel.</message>
    </code>
    <code hex="003B" severity="Error" name="ScErrOpenDbShmSegToNotifyClients">
      <message>The IPC monitor failed to open the database shared memory segment and is unable to notify the clients.</message>
    </code>
    <code hex="003C" severity="Error" name="ScErrIPCMonOpenDbShmSegUnknownEx">
      <message>The IPC monitor caught an unknown exception while trying to open database IPC shared memory segments.</message>
    </code>
    <code hex="003D" severity="Error" name="ScErrIPCMonUnknownProessTypeExit">
      <message>The IPC monitor got an unknown proess type exit.</message>
    </code>
    <code hex="003E" severity="Error" name="ScErrOpenProcessFailedRegCliProc">
      <message>The IPC monitor is trying to register a client process but OpenProcess() failed.</message>
    </code>
    <code hex="003F" severity="Error" name="ScErrTheOwnerIDMatchButNotThePID">
      <message>The IPC monitor unregistration failed. The owner ID matches but not the PID.</message>
    </code>
    <code hex="0040" severity="Error" name="ScErrThePIDMatchButNotTheOwnerID">
      <message>The IPC monitor unregistration failed. The PID matches but not the owner ID.</message>
    </code>
    <code hex="0041" severity="Error" name="ScErrCleanupToOpenTheDBIPCShmSeg">
      <message>The IPC monitor cleanup failed. Could not open the IPC database shared memory segment.</message>
    </code>
    <code hex="0042" severity="Error" name="ScErrIPCMonitorCleanupWaitFailed">
      <message>The IPC monitor was not notified. Wait failed.</message>
    </code>
    <code hex="0043" severity="Error" name="ScErrOutOfDedicatedAddressSpace">
      <message>Operation failed because needed memory couldn't be allocated within dedicated address space</message>
    </code>

  </facility>

  <!--
    Startup and shutdown error codes. Group contains codes for errors occuring during startup or shutdown.
    Usually caused by a faulty installation or faulty configuration settings. 
  -->
  <facility name="StartupAndShutdown" hex="0002">
    <code hex="0001" severity="Error" name="ScErrAppAlreadyStarted">
      <message>A Starcounter process with the specified name is already started.</message>
    </code>
    <code hex="0002" severity="Error" name="ScErrBadBaseDirectoryConfig">
      <message>Base directory (baseDirectory) missing from config or invalid.</message>
      <remarks>
        Applies if the specified directory doesn't exists or is invalid (for example if the
        specified path indicates a file), or if a base directory isn't specified when one is
        required.
      </remarks>
    </code>
    <code hex="0003" severity="Error" name="ScErrBadTempDirectoryConfig">
      <message>Temp directory (tempDirectory) missing from config or invalid.</message>
      <remarks>
        Applies if the specified directory doesn't exists or is invalid (for example if the
        specified path indicates a file).
      </remarks>
    </code>
    <code hex="0004" severity="Error" name="ScErrBadImageDirectoryConfig">
      <message>Image directory (imageDirectory) missing from config or invalid.</message>
      <remarks>
        Applies if the specified directory doesn't exists or is invalid (for example if the
        specified path indicates a file), or if a image directory isn't specified when one
        is required.
      </remarks>
    </code>
    <code hex="0005" severity="Error" name="ScErrBadTLogDirectoryConfig">
      <message>
        The transaction log directory (transactionLogDirectory) is missing from config or invalid.
      </message>
      <remarks>
        Applies if the specified directory doesn't exists or is invalid (for example if the
        specified path indicates a file), or if a transaction log directory isn't specified
        when one is required.
      </remarks>
    </code>
    <!--
    <code hex="0006" severity="Error" name="ScErrBadServerBacklogConfig">
      <message>The backlog configuration for the TCP/IP interface (serverBacklog) is invalid.</message>
    </code>
    <code hex="0007" severity="Error" name="ScErrBadServerEndpointConfig">
      <message>The endpoint configuration for the TCP/IP interface (serverEndPoint) is invalid.</message>
    </code>
    <code hex="0008" severity="Error" name="ScErrBadLogsEndpointConfig">
      <message>The endpoint configuration for the log server (logServerEndPoint) is invalid.</message>
    </code>
    <code hex="0009" severity="Error" name="ScErrBadInputDirectoryConfig">
      <message>The input directory configuration (inputDirectory) is invalid.</message>
      <remarks>
        Likely, the specified path doesn't exist or is not a directory. 
      </remarks>
    </code>
    <code hex="000A" severity="Error" name="ScErrBadOutpDirectoryConfig">
      <message>The output directory configuration (outputDirectory) is invalid.</message>
      <remarks>
        Likely, the specified path doesn't exist or is not a directory. 
      </remarks>
    </code>
    <code hex="000B" severity="Error" name="ScErrBadMaxIoopBytesConfig">
      <message>Bad max IOOP size configuration (maxIoopBytes or maxIoopBytes_TLOG).</message>
      <remarks>
        <para>
          Max IOOP size but align with sector size and some configurations has
          specific minimum and maximum value.
        </para>
        <para>
          This error code is obsolete in current version. It's no longer
          possible for user to configure maxIoopBytes or maxIoopBytes_TLOG.
        </para>
      </remarks>
    </code>
-->
    <code hex="000C" severity="Error" name="ScErrCantInitializeClr">
      <message>Unable to initialize the CLR.</message>
    </code>
    <code hex="000D" severity="Error" name="ScErrCantLoadHostEnvironment">
      <message>Unable to load host environment.</message>
    </code>
    <code hex="000E" severity="Error" name="ScErrLogModuleNotFound">
      <message>
        The operation failed because sccorelog.dll or one of the functions it exports
        couldn't be loaded.
      </message>
      <remarks>Most likely caused by a faulty installation.</remarks>
    </code>
    <code hex="000F" severity="Error" name="ScErrImageStorageMismatch">
      <message>
        The properties of the different disk drives used to store the image files
        don't have compatible configuration (do they have the same sector sizes?).
      </message>
    </code>
    <code hex="0010" severity="Error" name="ScErrImageStorageIncompatible">
      <message>
        The properties of the disk drive doesn't match the database image (is the disk
        drive is configured for a different sector size than the image is built for?).
      </message>
    </code>
    <code hex="0011" severity="Error" name="ScErrWrongDatabaseVersion">
      <message>
        The database files are build for a different Starcounter version and are not
        compatible with the current version.
      </message>
    </code>
    <code hex="0012" severity="Error" name="ScErrCantGetPrivilegesNeeded">
      <message>Could not acquire the privileges needed for the operation to complete successfully.</message>
      <remarks>
        This error code is obsolete in current version.
      </remarks>
    </code>
    <!--
    <code hex="0013" severity="Error" name="ScErrBadSessionMaxIdleConfig">
      <message>Session configuration for max idle minutes (sessionMaxIdleMinutes) is invalid.</message>
    </code>
    <code hex="0014" severity="Error" name="ScErrBadSessionDormantConfig">
      <message>Session configuration for dormant minutes (sessionDormantMinutes) is invalid.</message>
    </code>
    <code hex="0015" severity="Error" name="ScErrBadSqlProcPortConfig">
      <message>Configuration for SQL process port (sqlProcessPort) is invalid.</message>
    </code>
-->
    <code hex="0016" severity="Error" name="ScErrDatabaseFileMismatch">
      <message>
        Attempt to load database files from different databases was detected.
      </message>
      <remarks>
        This means that one of the image files, the transaction log or all three files
        were created for different databases.
      </remarks>
    </code>
    <code hex="0017" severity="Error" name="ScErrDatabaseLangUnsupported">
      <message>
        One of more of the languages the database is configured for isn't supported by
        the current system.
      </message>
    </code>
    <code hex="001B" severity="Error" name="ScErrCodeLoaderError">
      <message>Code loder error.</message>
      <remarks>
        General error produced by the code loader component. This error indicates that an
        operation during startup requiered some code to be accessed via the .NET reflection
        engine and that the loader cound not satisfy the request because of an error fetching
        the needed data. This usually indicates version mismatches or missing pe-files in the
        runtime library. The error lines up with one (or several) more specific errors. The
        later contains more detailed information about what specific code that couldnt load
        and can be found in the error log. This error ends up in the critical log (causing the
        database to fail startup). A corresponding and more specific error at the same time is
        written to the error log, describing what assembly failed and how to get even more error
        information.
      </remarks>
    </code>
    <!--
    <code hex="001C" severity="Error" name="ScErrCodeTypeNotFound">
      <message>Class or type not found.</message>
      <remarks>
        This error indicates that a .NET type was requested by its name but the code loader was
        unable to find it in the application code currently loaded. Results in a code loader error.
        See above. When this error occurs, the name of the type will be revealed in the error log.
        Also, additional information of the full set of loaded assemblies can be found in the notice
        log, using the same routine as described in the error below.
      </remarks>
    </code>
-->
    <code hex="001D" severity="Error" name="ScErrTypesLoadError">
      <message>Error inspecting assembly.</message>
      <remarks>
        <para>